POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: bearer aaJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvcmdlIiwiaWQiOiI2MjRiMWRhMTRmNTk3NGNiMzNiNTE2MTgiLCJpYXQiOjE2NDkxNjQzODMsImV4cCI6MTY0OTE2Nzk4M30.Ffs-mOF1ZxnzZjgyVZTWE5ZnEro49omDV0GWHOV4Kpw


{
    "title": "HAPPYYYY2",
    "author": "Medd",
    "url": "www"
}