POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
    "title": "Blog Jorge with userIDs",
    "author": "Me",
    "url": "https://testingbrear.com/",
    "userId": "624b1da14f5974cb33b51618"
}