POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
    "title": "Blog Jorge with userIDs",
    "author": "Me",
    "url": "https://testingbrear.com/",
    "userId": "624c26f46083c58d30f86565"
}